name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cppcheck in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/code yhl0607/static-analysis:latest \
          cppcheck --enable=all --inconclusive --std=c++17 --suppress=missingIncludeSystem /code

      - name: Run Scan Build in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/code yhl0607/static-analysis:latest \
          bash -c "cd /code/ex01/src && scan-build g++ -o my_program *.cpp"


