name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang-tools cppcheck -y

      - name: List directories (for debugging)
        run: |
          ls -R

      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --std=c++17 --suppress=missingIncludeSystem .

      - name: Run Scan Build
        run: |
          cd ex01/src
          find . -name "*.cpp" -exec scan-build g++ -o my_program {} +
